version: '3'
services:
  boilerplate-nestjs-dev:
    container_name: boilerplate-nestjs-dev
    build: .
    ports:
      - 8080:3000
    environment:
      POSTGRES_HOST: postgres:123123@postgres:5432
      PORT: 3000
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: boilerplate